### ISSUE TITLE
does not work with collectstatic when CachedStaticFilesStorage is enabled

### ISSUE THREAD

**Issue by martey** [armstrong/armstrong#86]
I am using Django 1.4.5 and Armstrong 12.03.1.

Traceback of collectstatic command:

> Traceback (most recent call last):
>   File "/home/nerve/envs/2013-02-20/bin/armstrong", line 9, in <module>
>     load_entry_point('armstrong.cli==1.1.1', 'console_scripts', 'armstrong')()
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/armstrong/cli/main.py", line 93, in main
>     func(*_kwargs)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/armstrong/cli/main.py", line 113, in call_django
>     execute_manager(settings, argv=new_argv)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 459, in execute_manager
>     utility.execute()
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
>     self.execute(_args, *_options.**dict**)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
>     output = self.handle(_args, **options)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/core/management/base.py", line 371, in handle
>     return self.handle_noargs(**options)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 163, in handle_noargs
>     collected = self.collect()
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 120, in collect
>     for original_path, processed_path, processed in processor:
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 226, in post_process
>     content = pattern.sub(converter, content)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 167, in converter
>     hashed_url = self.url(unquote(joined_result), force=True)
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 114, in url
>     hashed_name = self.hashed_name(clean_name).replace('\', '/')
>   File "/home/nerve/envs/2013-02-20/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 74, in hashed_name
>     (clean_name, self))
> ValueError: The file 'ckeditor/plugins/uicolor/yui/assets/bg-h.gif' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x257bf90>.

I think that this is because CachedStaticFilesStorage rewrites CSS in order to append hashsums to the end of static files, and the missing files are referenced by:
- `armstrong/hatband/static/ckeditor/plugins/uicolor/yui/assets/yui.css` (`bg-h.gif` and `bg-v.gif`).
- `armstrong/hatband/static/visualsearch/visualsearch.css` (`cancel-search.png` and `search_glyph.png`)
- `armstrong/apps/images/static/colorbox/colorbox.css` (`borderTopLeft.png`, `borderTopCenter.png`, `borderTopRight.png`, `borderBottomLeft.png`, `borderBottomCenter.png`, `borderBottomRight.png`, `borderMiddleLeft.png`, `borderMiddleCenter.png`, and `borderMiddleRight.png`)

I was able to work around this by creating empty files in my application's static directory, but think it would probably be better if Armstrong either provided these files, or modified the relevant stylesheets in order not to include them.

**Comment by tswicegood** [comment]
Hmm.  Looks like there's a few things missing in `armstrong.hatband` and `armstrong.apps.images` that are causing this.  Thanks for the head's up, @martey!

**Comment by odinho** [comment]
Some plugins did change with the ckeditor version change yes, and maybe I also didn't include the same set that was used at the last include. But there seems to be other files missing too, so it's hopefully not really a pure regression from 19?

**Comment by martey** [comment]
@Velmont, I was not using the changes in your pull request when I ran into this issue, so it is not a regression. However, if the ckeditor 4.1.1 CSS files reference images that are not included by default, or if you should removed some images, your pull request might have the same issue.

**Comment by tswicegood** [comment]
Oh!  Sorry for the confusion guys.  I was just thinking that PR 19 for hatband might solve this problem.
